dist: precise # https://github.com/travis-ci/travis-ci/issues/8331
sudo: false
cache: bundler
bundler_args: --no-deployment
branches:
  only: master
rvm:
  - 2.2
  - 2.3
  - 2.4
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
script: bundle exec rake $TASK
env:
  global:
    - TASK=test
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails4.2.gemfile
  include:
    - rvm: 2.4
      env:
        - TASK=rubocop
