rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
gemfile:
  - gemfiles/ar_32.gemfile
  - gemfiles/ar_40.gemfile
  - gemfiles/ar_41.gemfile
  - gemfiles/ar_42.gemfile
bundler_args: --no-deployment
script: "bundle exec rake test"
before_install:
  - gem update --system
  - gem update bundler
